<?php

require_once(__DIR__ . '/../../../config.php');

// Nginx preserves the original clean URL in this header.
// Fall back to REQUEST_URI for direct access.
$requesturi = $_SERVER['HTTP_X_CUSTOMCLEANURL_URI'] ?? $_SERVER['REQUEST_URI'];

// Prevent route.php from loading itself recursively.
// This was causing repeated POST /local/customcleanurl/route.php
// requests and eventually HTTP 500 errors.
if ($requesturi === '/local/customcleanurl/route.php') {
    error_log('CUSTOMCLEANURL DEBUG: route.php called itself - stopping recursion');
    http_response_code(500);
    exit('CustomCleanURL route recursion detected');
}

// Resolve the clean URL.
$responsedata = \local_customcleanurl\local\helper::check_requesturl($requesturi);

// Debug logging.
error_log('CUSTOMCLEANURL DEBUG requesturi=' . $requesturi);
error_log('CUSTOMCLEANURL DEBUG method=' . ($_SERVER['REQUEST_METHOD'] ?? 'UNKNOWN'));
error_log('CUSTOMCLEANURL DEBUG urltype=' . ($responsedata['urltype'] ?? ''));
error_log('CUSTOMCLEANURL DEBUG moodleurl=' . ($responsedata['moodleurl'] ?? ''));
error_log('CUSTOMCLEANURL DEBUG filepath=' . ($responsedata['filepath'] ?? ''));

if (!empty($responsedata['status'])) {

    $urltype = $responsedata['urltype'] ?? '';
    $moodleurl = $responsedata['moodleurl'] ?? '';
    $filepath = $responsedata['filepath'] ?? '';
    $param = $responsedata['param'] ?? [];

    /*
     * Custom Clean URL route test.
     */
    if ($urltype === 'customcleanurl_routetest') {
        header('Content-Type: application/json');
        echo json_encode(['status' => true]);
        exit;
    }

    /*
     * Some Moodle module URLs need to be redirected
     * to their original Moodle URL.
     */
    $redirecturltype = [
        'mod_page_view',
        'mod_resource_view',
        'mod_folder_view',
        'mod_url_view',
        'mod_url_index',
        'mod_imscp_view',
        'mod_bigbluebuttonbn_view',
    ];

    if (!empty($moodleurl) && in_array($urltype, $redirecturltype, true)) {
        redirect($moodleurl);
        exit;
    }

    /*
     * Handle 404 through the plugin's 404 handler.
     */
    if ($urltype === '404') {
        header('HTTP/1.0 404 Not Found');
        http_response_code(404);

        $_SERVER['REDIRECT_STATUS'] = '404';

        if (!empty($filepath) && is_file($filepath)) {
            chdir(dirname($filepath));
            require($filepath);
        }

        exit;
    }

    /*
     * For clean course URLs, tell Moodle what the internal
     * Moodle URL is.
     *
     * Example:
     * /course/learningplex tutorials
     * becomes internally:
     * /course/view.php?id=758
     *
     * This helps Moodle generate the correct internal links.
     */
    if ($urltype === 'customcleanurl_courseurl' && !empty($moodleurl)) {
        $PAGE->set_url($moodleurl);
    }

    /*
     * Pass resolved parameters to Moodle.
     */
    foreach ($param as $key => $value) {
        $_GET[$key] = $value;
    }

    /*
     * Execute the resolved Moodle PHP file.
     *
     * IMPORTANT:
     * Never allow route.php to require itself.
     */
    if (!empty($filepath) && is_file($filepath)) {

        // Extra safety check against self-inclusion.
        $currentroute = realpath(__FILE__);
        $targetfile = realpath($filepath);

        if ($targetfile !== false && $currentroute === $targetfile) {
            error_log(
                'CUSTOMCLEANURL DEBUG: prevented self-inclusion of route.php'
            );

            http_response_code(500);
            exit('CustomCleanURL route recursion detected');
        }

        /*
         * Moodle forms use $FULLME as the default form action.
         *
         * Because this request entered through route.php,
         * $FULLME can otherwise remain:
         *
         * /local/customcleanurl/route.php
         *
         * Set it to the resolved internal Moodle URL so forms
         * submit directly to the original Moodle PHP endpoint.
         */
        global $FULLME;

        if (!empty($moodleurl)) {
            $FULLME = $moodleurl;
        }

        chdir(dirname($filepath));
        require($filepath);
        exit;
    }
}

/*
 * If the request could not be resolved, return the
 * response generated by the plugin.
 */
if (!empty($responsedata['message'])) {
    echo $responsedata['message'];
} else {
    http_response_code(404);
    echo 'Page not found';
}

exit;
